# Generated by Django 4.0.3 on 2022-05-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='coupon',
            new_name='code',
        ),
    ]
