# Generated by Django 4.0.3 on 2022-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
